[workspace]
resolver = "2"

members = ["sidecar"]

[workspace.package]
authors = ["code0xff <ian.jungyong.um@gmail.com>"]
edition = "2021"
homepage = "https://github.com/NoirHQ/sidecar"
license = "Apache-2.0"
publish = false
repository = "https://github.com/NoirHQ/sidecar"

[workspace.dependencies]
anyhow = "1"
axum = "0.8"
clap = { version = "4.5", features = ["derive"] }
jsonrpsee = { version = "0.24", features = ["server"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.44", features = ["full"] }
toml = "0.8"
tower = { version = "0.5", features = ["full"] }
tower-http = { version = "0.6", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
